### ISSUE TITLE
`vim.lsp.buf.format()` formats, but `:Format` does not

### ISSUE THREAD

**Issue by iduuck** [lukas-reineke/lsp-format.nvim#73] opened 2023-03-21 10:45 UTC
I am currently developing several features for [trpc](https://github.com/trpc/trpc), but the problem here is, that the formatting is not working for me properly. My dotfiles are at [iduuck/dots](https://github.com/iduuck/dots).

Saw #70, but didn't help me, since the formatter **is working** on other projects properly (also not using null-ls here).

I will **try** to get a minimal repro done, but I am not sure, when...

---

`:LspLog` is the following:

```
[DEBUG][2023-03-21 11:55:03] .../lua/vim/lsp.lua:1381	"LSP[eslint]"	"client.request"	2	"textDocument/codeAction"	{  context = {    diagnostics = {}  },  range = {    ["end"] = <1>{      character = 0,      line = 20    },    start = <table 1>  },  textDocument = {    uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"  }}	<function 1>	17
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:285	"rpc.send"	{  id = 61,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = {}    },    range = {      ["end"] = <1>{        character = 0,        line = 20      },      start = <table 1>    },    textDocument = {      uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"    }  }}
[DEBUG][2023-03-21 11:55:03] .../lua/vim/lsp.lua:1381	"LSP[tsserver]"	"client.request"	4	"textDocument/codeAction"	{  context = {    diagnostics = {}  },  range = {    ["end"] = <1>{      character = 0,      line = 20    },    start = <table 1>  },  textDocument = {    uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"  }}	<function 1>	17
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:285	"rpc.send"	{  id = 44,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = {}    },    range = {      ["end"] = <1>{        character = 0,        line = 20      },      start = <table 1>    },    textDocument = {      uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"    }  }}
[DEBUG][2023-03-21 11:55:03] .../lua/vim/lsp.lua:1381	"LSP[tailwindcss]"	"client.request"	5	"textDocument/codeAction"	{  context = {    diagnostics = {}  },  range = {    ["end"] = <1>{      character = 0,      line = 20    },    start = <table 1>  },  textDocument = {    uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"  }}	<function 1>	17
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:285	"rpc.send"	{  id = 43,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = {}    },    range = {      ["end"] = <1>{        character = 0,        line = 20      },      start = <table 1>    },    textDocument = {      uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"    }  }}
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:388	"rpc.receive"	{  id = 61,  jsonrpc = "2.0",  result = {}}
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:388	"rpc.receive"	{  id = 43,  jsonrpc = "2.0"}
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:388	"rpc.receive"	{  id = 44,  jsonrpc = "2.0",  result = {}}
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:285	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didSave",  params = {    textDocument = {      uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"    }  }}
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:285	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didSave",  params = {    textDocument = {      uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"    }  }}
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:285	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didSave",  params = {    textDocument = {      uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"    }  }}
[DEBUG][2023-03-21 11:55:03] .../lua/vim/lsp.lua:1381	"LSP[eslint]"	"client.request"	2	"textDocument/formatting"	{  options = {    insertSpaces = true,    tabSize = 2  },  textDocument = {    uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"  }}	<function 1>	17
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:285	"rpc.send"	{  id = 62,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = true,      tabSize = 2    },    textDocument = {      uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"    }  }}
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:388	"rpc.receive"	{  id = 62,  jsonrpc = "2.0",  result = {}}
[DEBUG][2023-03-21 11:55:03] .../lua/vim/lsp.lua:1381	"LSP[eslint]"	"client.request"	2	"textDocument/codeAction"	{  context = {    diagnostics = {}  },  range = {    ["end"] = <1>{      character = 0,      line = 20    },    start = <table 1>  },  textDocument = {    uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"  }}	<function 1>	17
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:285	"rpc.send"	{  id = 63,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = {}    },    range = {      ["end"] = <1>{        character = 0,        line = 20      },      start = <table 1>    },    textDocument = {      uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"    }  }}
[DEBUG][2023-03-21 11:55:03] .../lua/vim/lsp.lua:1381	"LSP[tsserver]"	"client.request"	4	"textDocument/codeAction"	{  context = {    diagnostics = {}  },  range = {    ["end"] = <1>{      character = 0,      line = 20    },    start = <table 1>  },  textDocument = {    uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"  }}	<function 1>	17
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:285	"rpc.send"	{  id = 45,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = {}    },    range = {      ["end"] = <1>{        character = 0,        line = 20      },      start = <table 1>    },    textDocument = {      uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"    }  }}
[DEBUG][2023-03-21 11:55:03] .../lua/vim/lsp.lua:1381	"LSP[tailwindcss]"	"client.request"	5	"textDocument/codeAction"	{  context = {    diagnostics = {}  },  range = {    ["end"] = <1>{      character = 0,      line = 20    },    start = <table 1>  },  textDocument = {    uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"  }}	<function 1>	17
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:285	"rpc.send"	{  id = 44,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = {}    },    range = {      ["end"] = <1>{        character = 0,        line = 20      },      start = <table 1>    },    textDocument = {      uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"    }  }}
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:388	"rpc.receive"	{  id = 63,  jsonrpc = "2.0",  result = {}}
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:388	"rpc.receive"	{  id = 44,  jsonrpc = "2.0"}
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:388	"rpc.receive"	{  id = 45,  jsonrpc = "2.0",  result = {}}
```

**Comment by iduuck** [comment] 2023-03-21 10:48
Just to add this: `:EslintFixAll` is also not working, so this might be an issue with the LSP itself?

**Comment by lukas-reineke** [comment] 2023-03-23 06:05
from the logs you posted it looks like the response for the format request is empty

```
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:285	"rpc.send"	{  id = 62,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = true,      tabSize = 2    },    textDocument = {      uri = "file:///Users/nick/dev/trpc/packages/client/src/createTRPCClient.ts"    }  }}
[DEBUG][2023-03-21 11:55:03] .../vim/lsp/rpc.lua:388	"rpc.receive"	{  id = 62,  jsonrpc = "2.0",  result = {}}
```

This is a problem with the LSP, I can't help with that, sorry.

**Comment by NickHu** [comment] 2023-04-21 13:03
I have also noticed this plugin has stopped working since I switched to neovim 0.9, when vim.lsp.buf.formatting* options were removed.

**Comment by iduuck** [comment] 2023-04-21 22:39
@NickHu It works for me. What is your configuration?

**Comment by khjorth** [comment] 2024-01-19 22:29
`:Format` is broken for me too, and I suspect it's caused by #75, after which it seems necessary to supply `format(options)` with a map that contains the correct value for `buf`. I don't think the user commands have been updated to reflect this, but perhaps I'm missing something.

Formatting works if I manually call `format` with `buf` set.

But #75 was merged after the present report, so it can't be the cause of OP's issue.

**Closed** 2024-01-24 06:05 UTC
